default: &default
  adapter: <%= ENV["DB_ADAPTER"] %>
  encoding: unicode
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  database: <%= ENV["DB_NAME"] %>

test:
  <<: *default
  database: db_test

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
